dds_music_app/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),
]

dds_music_app/albums/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:album_id>', views.album_info, name='album_info'),
]

dds_music_app/artists/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('<int:artist_id>', views.artist_info, name='artist_info'),
]

dds_music_app/dds_music_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('songs/', include('songs.urls')),
    path('albums/', include('albums.urls')),
    path('artists/', include('artists.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dds_music_app/pages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
]

dds_music_app/songs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search_song', views.search_song, name='search_song'),
    path('<int:song_id>', views.song_info, name='song_info'),
]

dds_music_app/accounts/models.py
from django.db import models

# Create your models here.

dds_music_app/albums/models.py
from django.db import models
from datetime import datetime
from artists.models import Artist

class Album(models.Model):
    name = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    album_cover = models.ImageField(upload_to='album_covers')
    date_published = models.DateTimeField(default=datetime.now, blank=True)
    genre = models.CharField(max_length=200, default='pop')

    def __str__(self):
        return self.name

class Song(models.Model):
    name = models.CharField(max_length=200)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file = models.FileField(upload_to='songs/')
    
    def __str__(self):
        return self.name

dds_music_app/artists/models.py
from django.db import models
from datetime import datetime

class Artist(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to='artist_photos')
    description = models.TextField(blank=True)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    
    # to set the main field
    def __str__(self):
        return self.name

dds_music_app/pages/models.py
from django.db import models

# Create your models here.

dds_music_app/songs/models.py
from django.db import models

# Create your models here.

dds_music_app/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

def register(request):
    if request.method == 'POST':
        # Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password == password2:
            # Check username collision
            if User.objects.filter(username=username).exists():
                print(username, 'already exists')
                messages.error(request, 'username is taken!')
                return redirect('register')

            # Check emial collision
            if User.objects.filter(email=email).exists():
                messages.error(request, 'email already exists')
                return redirect('register')

            # update the user details in the database.
            user = User.objects.create_user(username=username, password=password, email=email, first_name=first_name, last_name=last_name)
            # login after register
            # auth.login(request, user)
            # messages.success(request, 'You are now logged in')
            # return redirect('index')

            # saving into the database
            user.save()
            messages.success(request, 'You can now login.')
            return redirect('login')
        else:
            messages.error(request, 'Passwords don\'t match!')
            return redirect('register')
    else:
        return render(request, 'accounts/register.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request, "You are now logged in.")
            return redirect('dashboard')
        else:
            messages.error(request, "Invalid credentials")
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, "You are now logged out")
        return redirect('index')
    return redirect('index')

def dashboard(request):
    return render(request, 'accounts/dashboard.html')

dds_music_app/albums/views.py
from django.shortcuts import render, get_object_or_404
from .models import Album, Song

def index(request):
    albums = Album.objects.order_by('-date_published')

    context = {
        'albums':albums
    }
    return render(request, 'albums/albums.html', context)

def album_info(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {
        'album': album
    }
    return render(request, 'albums/album_info.html', context)

dds_music_app/artists/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Artist

def artist_info(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    context = {
        'artist': artist
    }
    return render(request, 'artists/artist_info.html', context);

dds_music_app/pages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from albums.models import Song, Album

def index(request):
    albums = Album.objects.order_by('-date_published')[:3]

    context = {
        'albums':albums
    }

    return render(request, 'pages/index.html', context)

def about(request):
    return render(request, 'pages/about.html')

dds_music_app/songs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from albums.models import Song, Album

# To-do!
def song_info(request, song_id):
    return render()

def search_song(request):
    queryset_list = Song.objects.all()
    # Keywords
    if 'keywords' in request.GET:
        print("Keywords :", request.GET['keywords'])
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(name__icontains=keywords)
        else:
            print('No keywords')
   

    context = {
        'songs': queryset_list,
        'values':request.GET
    }

    return render(request, 'songs/search_song.html', context)

def song_info(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    context = {
        'song': song
    }
    return render(request, 'songs/song_info.html', context)

dds_music_app/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block content %}

{% if user.is_authenticated %}
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
            <br>
          <h2 class="display-4">Your Favourite Songs</h2>
          <hr>
        </div>
      </div>
    </div>
 
    <div class="container">
        <div class="col-md-12 m-auto">
            <div class="card mb-1">
                <div class="card-body">
                    <a href="#" class="float-left" title="Remove from favourites"> <i class="fas fa-heart text-secondary"></i></a>
                    <div class="row">
                        <div class="col-4"> <strong>Name</strong></div>
                        <div class="col-4 text-center"> <strong>Artist</strong></div>
                        <div class="col-4 text-center"> <strong>Album</strong></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% else %}

{% endif %}

{% endblock %}

dds_music_app/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}


  <section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-sign-in-alt"></i> Login</h4>
            </div>
            <div class="card-body">
              <!-- Alerts! -->
              {% include 'partials/_alerts.html' %}
              <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>

                <input type="submit" value="Login" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

dds_music_app/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}

<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-user-plus"></i> Register</h4>
            </div>
            <div class="card-body">
                <!-- Alerts! -->
                {% include 'partials/_alerts.html' %}
                <form action="{% url 'register' %}" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                  <label for="first_name">First Name</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="last_name">Last Name</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password">Confirm Password</label>
                  <input type="password" name="password2" class="form-control" required>
                </div>
                <input type="submit" value="Register" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock %}

dds_music_app/templates/albums/album_info.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<div class="container">
    <div class="row text-center text-secondary">
      <div class="col-md-12">
          <br>
        <h2 class="display-4">{{album.name}}</h2>
        <h4 class="text-secondary">by <a href="{% url 'artist_info' album.artist.id %}">{{ album.artist.name }} </a></h4>
        <hr>
      </div>
    </div>
</div>

<div class="container">

    {% for song in album.song_set.all %}
    
    <div class="col-md-12 m-auto">
        <div class="card mb-1">
            <div class="card-body">
                {% if user.is_authenticated %}
                    <a href="#" class="float-left" title="Remove from favourites"> <i class="fas fa-heart text-secondary"></i></a>
                {% endif %}
                <div class="row">
                    <a href="{% url 'song_info' song.id %}" class="col-12 text-center"> 
                        <strong>{{song.name}}</strong>
                    </a>
                    
                </div>
            </div>
        </div>
    </div>    
    {% endfor %}

</div>

  
{% endblock %}

dds_music_app/templates/albums/albums.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

{% endblock %}

dds_music_app/templates/albums/search.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

{% endblock %}

dds_music_app/templates/albums/songs.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}

{% endblock %}

dds_music_app/templates/artists/artist_home.html
{% extends 'base.html' %}

{% block content %}
<!-- albums -->
<section id="albums" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Albums of {{ artist.name }}</h3>
      <div class="row">
        {% for album in artist.album_set.all %}
            <!-- Album -->
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card album-preview">
                <img class="card-img-top" src="{{ album.album_cover.url }}" alt="">
                <div class="card-body">
                    <div class="album-heading text-center">
                    <h4 class="text-primary"> {{ album.name }}  </h4>
                    <p>
                    <i class="fas fa-user-astronaut text-secondary"></i> <a href="{% url 'artist_info' album.artist.id %}">{{ album.artist.name }}</a>  </p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                    <div class="col-6">
                        <i class="fas fa-compact-disc"></i> {{ album.genre }} </div>
                    </div>
                    <div class="row text-secondary pb-2">
                    <div class="col-12">
                        <i class="fas fa-clock"></i> Released {{ album.date_published | timesince }}</div>
                    </div>
                    <hr>
                    <a href="{% url 'album_info' album.id%}" class="btn btn-primary btn-block">More Info</a>
                </div>
                </div>
            </div>
        {% endfor %}
      </div>
  </div>
  
  </section>
{% endblock %}

dds_music_app/templates/artists/artist_info.html
{% extends 'base.html' %}

{% block content %}
<!-- albums -->
<section id="albums" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Albums of {{ artist.name }}</h3>
      <div class="row">
        {% for album in artist.album_set.all %}
            <!-- Album -->
            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card album-preview">
                <img class="card-img-top" src="{{ album.album_cover.url }}" alt="">
                <div class="card-body">
                    <div class="album-heading text-center">
                    <h4 class="text-primary"> {{ album.name }}  </h4>
                    <p>
                    <i class="fas fa-user-astronaut text-secondary"></i> <a href="{% url 'artist_info' album.artist.id %}">{{ album.artist.name }}</a>  </p>
                    </div>
                    <hr>
                    <div class="row py-2 text-secondary">
                    <div class="col-6">
                        <i class="fas fa-compact-disc"></i> {{ album.genre }} </div>
                    </div>
                    <div class="row text-secondary pb-2">
                    <div class="col-12">
                        <i class="fas fa-clock"></i> Released {{ album.date_published | timesince }}</div>
                    </div>
                    <hr>
                    <a href="{% url 'album_info' album.id%}" class="btn btn-primary btn-block">More Info</a>
                </div>
                </div>
            </div>
        {% endfor %}
      </div>
  </div>
  
  </section>
{% endblock %}

dds_music_app/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <!-- Custom -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DDS Music Library</title>
</head>
<body>
    <!-- Navbar -->
    {% include 'partials/_navbar.html' %}

    <!-- Main Content -->

    {% block content %} {% endblock %}

    <!-- Footer -->
    {% include 'partials/_footer.html' %}
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    
</body>
</html>

dds_music_app/templates/pages/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>This is about page.</h1>

{% endblock %}

dds_music_app/templates/pages/index.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<!-- Alerts! -->
{% include 'partials/_alerts.html' %}

<!-- Showcase -->
<section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            <i class="fas fa-music text-secondary"></i> Search DDS Music Library <i class="fas fa-headphones-alt text-secondary"></i> 
          </h1>
          <p class="lead">Each memory has a soundtrack of it's own. So search away!</p>
          <div class="search">
            <form action="{% url 'search_song' %}">
              <!-- Form Row 1 -->
              <div class="form-row">
                  <label class="sr-only">Keywords</label>
                  <input type="text" name="keywords" class="form-control centered" placeholder="Title of the song (e.g. Castle on the Hill, Circles)">
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <hr>

  <!-- albums -->
  <section id="albums" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Latest Albums</h3>
      <div class="row">
        {% if albums %}
            {% for album in albums %}
                <!-- Album -->
                <div class="col-md-6 col-lg-4 mb-4">
                  <div class="card album-preview">
                    <img class="card-img-top" src="{{ album.album_cover.url }}" alt="">
                    <div class="card-body">
                      <div class="album-heading text-center">
                        <h4 class="text-primary"> {{ album.name }}  </h4>
                        <p>
                        <i class="fas fa-user-astronaut text-secondary"></i> <a href="{% url 'artist_info' album.artist.id %}">{{ album.artist.name }}</a>  </p>
                      </div>
                      <hr>
                      <div class="row py-2 text-secondary">
                        <div class="col-6">
                            <i class="fas fa-compact-disc"></i> {{ album.genre }} </div>
                      </div>
                      <div class="row text-secondary pb-2">
                        <div class="col-12">
                          <i class="fas fa-clock"></i> Released {{ album.date_published | timesince }}</div>
                      </div>
                      <hr>
                      <a href="{% url 'album_info' album.id %}" class="btn btn-primary btn-block">More Info</a>
                    </div>
                  </div>
                </div>
            {% endfor %}
        {% else %}
        No Albums available
        {% endif %}
      </div>
  </div>
  
  </section>


{% endblock %}

dds_music_app/templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alter-dismissable text-center" role="alert">
                <button class="close" type="button" data-dismiss="alert">
                    <span aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        ERROR:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

dds_music_app/templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Madhu and Maruthi
</footer>

dds_music_app/templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">
          <li class="nav-item mr-3 active">
            <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-music text-secondary"></i><strong>  DDS Music Library</strong></a>
          </li>

          <li
            {% if '/' == request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'index' %}">Home</a>
          </li>
          
          <li
            {% if 'about' in request.path %}
            class="nav-item active mr-3"
            {% else %}
            class="nav-item mr-3"
            {% endif %}
          >
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
              <li 
                {% if 'register' in request.path %}
                  class="nav-item active mr-3"
                {% else %}
                  class="nav-item mr-3"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'dashboard' %}">
                  <i class="fas fa-user-plus"></i> <strong>Welcome, {{ user.username }}</strong> | [ Dashboard ]</a>
              </li>

              <li class="nav-item mr-3">
                <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                  <i class="fas fa-sign-out-alt"></i> Logout
                </a>
              </li>
              <form action="{% url 'logout' %}" id="logout" method="POST">
                {% csrf_token %}
                <input type="hidden">
              </form>
          {% else %}  
              <li 
                {% if 'register' in request.path %}
                  class="nav-item active mr-3"
                {% else %}
                  class="nav-item mr-3"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'register' %}">
                  <i class="fas fa-user-plus"></i> Register</a>
              </li>
              <li 
                {% if 'login' in request.path %}
                  class="nav-item active mr-3"
                {% else %}
                  class="nav-item mr-3"
                {% endif %}
              >
                <a class="nav-link" href="{% url 'login' %}">
                  <i class="fas fa-sign-in-alt"></i>

                  Login</a>
              </li>
          {% endif %}
        </ul>
      </div>
    </div>
</nav>

dds_music_app/templates/songs/search_song.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<!-- Alerts! -->
{% include 'partials/_alerts.html' %}

<!-- Showcase -->
<section id="showcase">
    <div class="container text-center">
      <div class="home-search p-5">
        <div class="overlay p-5">
          <h1 class="display-4 mb-4">
            <i class="fas fa-music text-secondary"></i> Search DDS Music Library <i class="fas fa-headphones-alt text-secondary"></i> 
          </h1>
          <p class="lead">Each memory has a soundtrack of it's own. So search away!</p>
          <div class="search">
            <form action="{% url 'search_song' %}">
              <!-- Form Row 1 -->
              <div class="form-row">
                  <label class="sr-only">Keywords</label>
                  <input type="text" name="keywords" class="form-control centered" placeholder="Title of the song (e.g. Castle on the Hill, Circles)"
                  value="{{ values.keywords }}"">
              </div>
              <button class="btn btn-secondary btn-block mt-4" type="submit">Search</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </section>

  <hr>

  <!-- albums -->
  <section id="albums" class="py-5">
    <div class="container">
      <h3 class="text-center mb-3">Results for the song query "{{ values.keywords }}"</h3>
      <div class="row">
        {% if songs %}
            {% for song in songs %}
                <!-- Album -->
                <div class="col-md-6 col-lg-4 mb-4">
                  <div class="card album-preview">
                    <img class="card-img-top" src="{{ song.album.album_cover.url }}" alt="">
                    <div class="card-body">
                      <div class="album-heading text-center">
                        <h4 class="text-primary"> {{ song.name }}  </h4>
                        <p>
                        <i class="fas fa-compact-disc text-secondary"></i>
                        Album: {{ song.album.name }} </p>
                      </div>
                      <hr>
                      <div class="row py-2 text-secondary">
                        <div class="col-12">
                          <i class="fas fa-user-astronaut"></i> {{ song.album.artist.name }} </div>
                      </div>
                      <div class="row py-2 text-secondary">
                        <div class="col-12">
                            <i class="fas fa-compact-disc"></i> {{ song.album.genre }} </div>
                      </div>
                      <div class="row text-secondary pb-2">
                        <div class="col-12">
                          <i class="fas fa-clock"></i> Released {{ song.album.date_published | timesince }}</div>
                      </div>
                      <hr>
                      <a href="{% url 'song_info' song.id %}" class="btn btn-primary btn-block">More Info</a>
                    </div>
                  </div>
                </div>
            {% endfor %}
        {% else %}
        No Songs available
        {% endif %}
      </div>
  </div>
  
  </section>


{% endblock %}

dds_music_app/templates/songs/song_info.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row text-center text-secondary">
      <div class="col-md-12">
        <br>
        <i class="fas fa-music text-secondary"></i> 
        <h2 class="display-4"><strong>{{song.name}}</strong> </h2>
        <hr>
      </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4 col-lg-4 mb-4"></div>
    <div class="col-md-4 col-lg-4 mb-4">
        <div class="card album-preview">
            <br>
            <p class="text-center">
                <audio controls>
                    <source src="{{ song.file.url }}" type="audio/mpeg">
                </audio>
            </p>
            <div class="card-body">
                <div class="album-heading text-center">
                <h4 class="text-primary"> {{ song.album.name }}  </h4>
                <p>
                    <i class="fas fa-user-astronaut text-secondary"></i> <a href="{% url 'artist_info' song.album.artist.id %}">{{ song.album.artist.name }}</a>
                </p>
                
                </div>
                <hr>
                <div class="row py-2 text-secondary">
                <div class="col-6">
                    <i class="fas fa-compact-disc"></i> {{ song.album.genre }} </div>
                </div>
                <div class="row text-secondary pb-2">
                <div class="col-12">
                    <i class="fas fa-clock"></i> Released {{ song.album.date_published | timesince }}</div>
                </div>
                <hr>
                <a href="{% url 'album_info' song.album.id %}" class="btn btn-primary btn-block">Go to Album</a>
            </div>
            <img class="card-img-top" src="{{ song.album.album_cover.url }}" alt="">
        </div>
    </div>

</div>


{% endblock %}